import {Kfz} from './kfz';

export const kfzdata: Array<Kfz> = [
    {usz: '0-1', stakr: 'Kraftfahrzeuge des Bundespräsidenten'},
    {usz: '0-2', stakr: 'Kraftfahrzeuge des Bundeskanzlers / der Bundeskanzlerin'},
    {usz: '0-3', stakr: 'Kraftfahrzeuge des Außenministers'},
    {usz: '0-4', stakr: 'Kraftfahrzeuge des ersten Staatssekretärs im Auswärtigen Amt'},
    {usz: '1-1', stakr: 'Kraftfahrzeuge des Bundestagspräsidenten'},
    {usz: 'A', stakr: 'Augsburg (Bayern)'},
    {usz: 'AA', stakr: 'Aalen / Ostalbkreis (Baden-Württemberg)'},
    {usz: 'AB', stakr: 'Aschaffenburg (Bayern)'},
    {usz: 'ABG', stakr: 'Altenburger Land (Thüringen)'},
    {usz: 'ABI', stakr: 'Anhalt-Bitterfeld (Sachsen-Anhalt)'},
    {usz: 'AC', stakr: 'Aachen (Nordrhein-Westfalen)'},
    {usz: 'AE', stakr: 'Auerbach / Vogtlandkreis (Sachsen)'},
    {usz: 'AH', stakr: 'Ahaus / Kreis Borken (Nordrhein-Westfalen)'},
    {usz: 'AIB', stakr: 'Bad Aibling / Landkreis München und Rosenheim (Bayern)'},
    {usz: 'AIC', stakr: 'Aichach-Friedberg (Bayern)'},
    {usz: 'AK', stakr: 'Altenkirchen / Westerwald (Rheinland-Pfalz)'},
    {usz: 'ALF', stakr: 'Alfeld / Landreis Hildesheim (Niedersachsen)'},
    {usz: 'ALZ', stakr: 'Alzenau / Landkreis Aschaffenburg (Bayern)'},
    {usz: 'AM', stakr: 'Amberg (Bayern)'},
    {usz: 'AN', stakr: 'Ansbach (Bayern)'},
    {usz: 'ANA', stakr: 'Annaberg / Erzgebirgskreis (Sachsen)'},
    {usz: 'ANG', stakr: 'Angermünde / Landkreis Uckermark (Brandenburg)'},
    {usz: 'ANK', stakr: 'Anklam / Landkreis Vorpommern-Greifswald (Mecklenburg-Vorpommern)'},
    {usz: 'AÖ', stakr: 'Altötting (Bayern)'},
    {usz: 'AP', stakr: 'Weimarer Land (Thüringen)'},
    {usz: 'APD', stakr: 'Apolda / Weimarer Land (Thüringen)'},
    {usz: 'ARN', stakr: 'Arnstadt / Ilm-Kreis (Thüringen)'},
    {usz: 'ART', stakr: 'Artern / Kyffhäuserkreis (Thüringen)'},
    {usz: 'AS', stakr: 'Amberg-Sulzbach (Bayern)'},
    {usz: 'ASL', stakr: 'Aschersleben / Salzlandkreis (Sachsen-Anhalt)'},
    {usz: 'ASZ', stakr: 'Aue-Schwarzenberg / Erzgebirgskreis (Sachsen)'},
    {usz: 'AT', stakr: 'Altentreptow / Mecklenburgische Seenplatte (Mecklenburg-Vorpommern)'},
    {usz: 'AU', stakr: 'Aue / Erzgebirgskreis (Sachsen)'},
    {usz: 'AUR', stakr: 'Aurich (Niedersachsen)'},
    {usz: 'AW', stakr: 'Ahrweiler (Rheinland-Pfalz)'},
    {usz: 'AZ', stakr: 'Alzey / Worms (Rheinland-Pfalz)'},
    {usz: 'AZE', stakr: 'Anhalt-Zerbst / Landkreis Anhalt-Bitterfeld(Sachsen-Anhalt)'},
    {usz: 'B', stakr: 'Berlin (Bln)'},
    {usz: 'BA', stakr: 'Bamberg (Bayern)'},
    {usz: 'BAD', stakr: 'Baden-Baden (Baden-Württemberg)'},
    {usz: 'BAR', stakr: 'Barnim (Brandenburg)'},
    {usz: 'BB', stakr: 'Böblingen (Baden-Württemberg)'},
    {usz: 'BBG', stakr: 'Bernburg / Salzlankreis (Sachsen-Anhalt)'},
    {usz: 'BBL', stakr: 'Brandenburgdenburg Landesregierung und Landtag'},
    {usz: 'BC', stakr: 'Biberach / Riß (Baden-Württemberg)'},
    {usz: 'BCH', stakr: 'Buchen / Neckar-Odenwald-Kreis (Baden-Württemberg)'},
    {usz: 'BD', stakr: 'Bundestag, Bundesrat, Bundesregierung'},
    {usz: 'BE', stakr: 'Beckum / Kreis Warendorf (Nordrhein-Westfalen)'},
    {usz: 'BED', stakr: 'Brand-Erbisdorf / Landkreis Mittelsachsen (Sachsen)'},
    {usz: 'BER', stakr: 'Bernau bei Berlin / Landkreis Barnim (Brandenburg)'},
    {usz: 'BF', stakr: 'Burgsteinfurt / Kreis Steinfurt (Nordrhein-Westfalen)'},
    {usz: 'BG', stakr: 'Bundesgrenzschutz'},
    {usz: 'BGL', stakr: 'Berchtesgadener Land (Bayern)'},
    {usz: 'BH', stakr: 'Bühl / Landkreis Rastatt (Baden-Württemberg)'},
    {usz: 'BI', stakr: 'Bielefeld (Nordrhein-Westfalen)'},
    {usz: 'BID', stakr: 'Biedenkopf / Landkreis Marburg-Biedenkopf (Hessen)'},
    {usz: 'BIN', stakr: 'Bingen / Landkreis Mainz-Bingen (Rheinland-Pfalz)'},
    {usz: 'BIR', stakr: 'Birkenfeld / Nahe und Idar-Oberstein (Rheinland-Pfalz)'},
    {usz: 'BIT', stakr: 'Bitburg / Eifelkreis Bitburg-Prüm (Rheinland-Pfalz)'},
    {usz: 'BIW', stakr: 'Bischofswerda / Landkreis Bautzen (Sachsen)'},
    {usz: 'BK', stakr: 'Backnang / Rems-Murr-Kreis (Baden-Württemberg), / Landkreis Börde (Sachsen-Anhalt)'},
    {usz: 'BKS', stakr: 'Bernkastel-Kues / Landkreis Bernkastel-Wittlich (Rheinland-Pfalz)'},
    {usz: 'BL', stakr: 'Balingen / Zollernalbkreis (Baden-Württemberg)'},
    {usz: 'BLB', stakr: 'Bad Berleburg / Kreis Siegen-Wittgenstein (Nordrhein-Westfalen)'},
    {usz: 'BLK', stakr: 'Burgenlandkreis (Sachsen-Anhalt)'},
    {usz: 'BM', stakr: 'Bergheim / Rhein-Erft-Kreis (Nordrhein-Westfalen)'},
    {usz: 'BN', stakr: 'Bonn (Nordrhein-Westfalen)'},
    {usz: 'BNA', stakr: 'Borna / Landkreis Leipzig (Sachsen)'},
    {usz: 'BO', stakr: 'Bochum (Nordrhein-Westfalen)'},
    {usz: 'BÖ', stakr: 'Landkreis Börde (Sachsen-Anhalt)'},
    {usz: 'BOH', stakr: 'Bocholt / Kreis Borken (Nordrhein-Westfalen)'},
    {usz: 'BOR', stakr: 'Borken / Kreis Borken (Nordrhein-Westfalen)'},
    {usz: 'BOT', stakr: 'Bottrop (Nordrhein-Westfalen)'},
    {usz: 'BP', stakr: 'Bundespolizei'},
    {usz: 'BRA', stakr: 'Brake / Landkreis Wesermarsch (Niedersachsen)'},
    {usz: 'BRB', stakr: 'Brandenburg an der Havel (Brandenburg)'},
    {usz: 'BRG', stakr: 'Burg bei Magdeburg / Landkreis Jerichower Land (Sachsen-Anhalt)'},
    {usz: 'BRK', stakr: 'Bad Brückenau / Landkreis Bad Kissingen (Bayern)'},
    {usz: 'BRL', stakr: 'Braunlage / Landkreis Goslar (Niedersachsen)'},
    {usz: 'BRV', stakr: 'Bremervörde / Landkreis Rotenburg - Wümme (Niedersachsen)'},
    {usz: 'BS', stakr: 'Braunschweig (Niedersachsen)'},
    {usz: 'BT', stakr: 'Bayreuth (Bayern)'},
    {usz: 'BTF', stakr: 'Bitterfeld / Landkreis Anhalt-Bitterfeld (Sachsen-Anhalt)'},
    {usz: 'BÜD', stakr: 'Büdingen / Wetteraukreis (Hessen)'},
    {usz: 'BÜS', stakr: 'Büsingen am Hochrhein (Baden-Württemberg)'},
    {usz: 'BÜZ', stakr: 'Bützow / Landkreis Rostock (Mecklenburg-Vorpommern)'},
    {usz: 'BW', stakr: 'Bundes-Wasser- und Schiffahrtsverwaltung'},
    {usz: 'BWL', stakr: 'Baden-Württemberg Landesregierung und Landtag'},
    {usz: 'BYL', stakr: 'Bayern Landesregierung und Landtag'},
    {usz: 'BZ', stakr: 'Bautzen (Sachsen)'},
    {usz: 'C', stakr: 'Chemnitz (Sachsen)'},
    {usz: 'CA', stakr: 'Calau / Landkreis Oberspreewald-Lausitz (Brandenburg)'},
    {usz: 'CAS', stakr: 'Castrop-Rauxel / Kreis Recklinghausen (Nordrhein-Westfalen)'},
    {usz: 'CB', stakr: 'Cottbus (Brandenburg)'},
    {usz: 'CE', stakr: 'Celle (Niedersachsen)'},
    {usz: 'CHA', stakr: 'Cham / Oberpfalz (Bayern)'},
    {usz: 'CLP', stakr: 'Cloppenburg (Niedersachsen)'},
    {usz: 'CLZ', stakr: 'Clausthal-Zellerfeld / Landkreis Goslar (Niedersachsen)'},
    {usz: 'CO', stakr: 'Coburg (Bayern)'},
    {usz: 'COC', stakr: 'Cochem a.d. Mosel / Landkreis Cochem-Zell (Rheinland-Pfalz)'},
    {usz: 'COE', stakr: 'Coesfeld / Westfalen (Nordrhein-Westfalen)'},
    {usz: 'CUX', stakr: 'Cuxhaven (Niedersachsen)'},
    {usz: 'CW', stakr: 'Calw (Baden-Württemberg)'},
    {usz: 'D', stakr: 'Düsseldorf (Nordrhein-Westfalen)'},
    {usz: 'DA', stakr: 'Darmstadt / Landkreis Darmstadt-Dieburg (Hessen)'},
    {usz: 'DAH', stakr: 'Dachau (Bayern)'},
    {usz: 'DAN', stakr: 'Dannenberg / Landkreis Lüchow-Dannenberg (Niedersachsen)'},
    {usz: 'DAU', stakr: 'Daun / Landkreis Vulkaneifel (Rheinland-Pfalz)'},
    {usz: 'DB', stakr: 'Deutsche Bahn'},
    {usz: 'DBR', stakr: 'Bad Doberan / Landkreis Rostock (Mecklenburg-Vorpommern)'},
    {usz: 'DD', stakr: 'Dresden (Sachsen)'},
    {usz: 'DE', stakr: 'Dessau / Landkreis Dessau-Roßlau (Sachsen-Anhalt)'},
    {usz: 'DEG', stakr: 'Deggendorf (Bayern)'},
    {usz: 'DEL', stakr: 'Delmenhorst (Niedersachsen)'},
    {usz: 'DGF', stakr: 'Dingolfing / Landkreis Dingolfing-Landau (Bayern)'},
    {usz: 'DH', stakr: 'Diepholz-Syke (Niedersachsen)'},
    {usz: 'DI', stakr: 'Dieburg / Landkreis Darmstadt-Dieburg (Hessen)'},
    {usz: 'DIL', stakr: 'Dillenburg / Lahn-Dill-Kreis (Hessen)'},
    {usz: 'DIN', stakr: 'Dinslaken / Kreis Wesel (Nordrhein-Westfalen)'},
    {usz: 'DIZ', stakr: 'Diez / Rhein-Lahn-Kreis (Rheinland-Pfalz)'},
    {usz: 'DKB', stakr: 'Dinkelsbühl / Landkreis Ansbach (Bayern)'},
    {usz: 'DL', stakr: 'Döbeln / Landkreis Mittelsachsen(Sachsen)'},
    {usz: 'DLG', stakr: 'Dillingen a.d. Donau (Bayern)'},
    {usz: 'DM', stakr: 'Demmin / Landkreis Mecklenburgische Seenplatte (Mecklenburg-Vorpommern)'},
    {usz: 'DN', stakr: 'Düren (Nordrhein-Westfalen)'},
    {usz: 'DO', stakr: 'Dortmund (Nordrhein-Westfalen)'},
    {usz: 'DON', stakr: 'Donauwörth / Landkreis Donau-Ries (Bayern)'},
    {usz: 'DU', stakr: 'Duisburg (Nordrhein-Westfalen)'},
    {usz: 'DÜW', stakr: 'Bad Dürkheim in Neustadt a.d. Weinstraße (Rheinland-Pfalz)'},
    {usz: 'DW', stakr: 'Dippoldiswalde / Landkreis Sächsische Schweiz-Osterzgebirge (Sachsen)'},
    {usz: 'DZ', stakr: 'Delitzsch / Landkreis Nordsachsen (Sachsen)'},
    {usz: 'E', stakr: 'Essen (Nordrhein-Westfalen)'},
    {usz: 'EA', stakr: 'Eisenach (Thüringen)'},
    {usz: 'EB', stakr: 'Eilenburg / Landkreis Nordsachsen (Sachsen)'},
    {usz: 'EBE', stakr: 'Ebersberg (Bayern)'},
    {usz: 'EBN', stakr: 'Ebern / Landkreis Haßberge (Bayern)'},
    {usz: 'EBS', stakr: 'Ebermannstadt / Landkreise Bayreuth, Forchheim und Kulmbach (Bayern)'},
    {usz: 'ECK', stakr: 'Eckernförde / Kreis Rendsburg-Eckernförde (Schleswig-Holstein)'},
    {usz: 'ED', stakr: 'Erding (Bayern)'},
    {usz: 'EE', stakr: 'Elbe-Elster (Brandenburg)'},
    {usz: 'EF', stakr: 'Erfurt (Thüringen)'},
    {usz: 'EG', stakr: 'Eggenfelden / Landkreis Rottal-Inn (Bayern)'},
    {usz: 'EI', stakr: 'Eichstätt (Bayern)'},
    {usz: 'EIC', stakr: 'Eichsfeld (Thüringen)'},
    {usz: 'EIL', stakr: 'Eisleben / Landkreis Mansfeld-Südharz (Sachsen-Anhalt)'},
    {usz: 'EIN', stakr: 'Einbeck / Landkreis Northeim (Niedersachsen)'},
    {usz: 'EIS', stakr: 'Eisenberg / Saale-Holzland-Kreis (Thüringen)'},
    {usz: 'EL', stakr: 'Emsland (Niedersachsen)'},
    {usz: 'EM', stakr: 'Emmendingen (Baden-Württemberg)'},
    {usz: 'EMD', stakr: 'Emden (Niedersachsen)'},
    {usz: 'EMS', stakr: 'Bad Ems / Rhein-Lahn-Kreis (Rheinland-Pfalz)'},
    {usz: 'EN', stakr: 'Ennepe / Ennepe-Ruhr-Kreis (Nordrhein-Westfalen)'},
    {usz: 'ER', stakr: 'Erlangen (Bayern)'},
    {usz: 'ERB', stakr: 'Erbach / Odenwaldkreis (Hessen)'},
    {usz: 'ERH', stakr: 'Erlangen-Höchstadt (Bayern)'},
    {usz: 'ERK', stakr: 'Erkelenz / Kreis Heinsberg (Nordrhein-Westfalen)'},
    {usz: 'ERZ', stakr: 'Erzgebirge / Erzgebirgskreis (Sachsen)'},
    {usz: 'ES', stakr: 'Esslingen am Neckar (Baden-Württemberg)'},
    {usz: 'ESB', stakr: 'Eschenbach in der Oberpfalz (Bayern)'},
    {usz: 'ESW', stakr: 'Eschwege / Werra-Meißner-Kreis (Hessen)'},
    {usz: 'EU', stakr: 'Euskirchen (Nordrhein-Westfalen)'},
    {usz: 'EW', stakr: 'Eberswalde / Landkreis Barnim (Brandenburg)'},
    {usz: 'F', stakr: 'Frankfurt/Main (Hessen)'},
    {usz: 'FB', stakr: 'Friedberg / Wetteraukreis (Hessen)'},
    {usz: 'FD', stakr: 'Fulda (Hessen)'},
    {usz: 'FDB', stakr: 'Friedberg / Landkreis Aichbach-Friedberg (Bayern)'},
    {usz: 'FDS', stakr: 'Freudenstadt (Baden-Württemberg)'},
    {usz: 'FEU', stakr: 'Feuchtwangen / Landkreis Ansbach (Bayern)'},
    {usz: 'FF', stakr: 'Frankfurt a.d. Oder (Brandenburg)'},
    {usz: 'FFB', stakr: 'Fürstenfeldbruck (Bayern)'},
    {usz: 'FG', stakr: 'Freiberg / Landkreis Mittelsachsen(Sachsen)'},
    {usz: 'FI', stakr: 'Finsterwalde / Landkreis Elber-Elster (Brandenburg)'},
    {usz: 'FKB', stakr: 'Frankenberg / Landkreis Waldeck-Frankenberg (Hessen)'},
    {usz: 'FL', stakr: 'Flensburg (Schleswig-Holstein)'},
    {usz: 'FLÖ', stakr: 'Flöha / Landkreis Mittelsachsen (Sachsen)'},
    {usz: 'FN', stakr: 'Friedrichshafen / Bodenseekreis (Baden-Württemberg)'},
    {usz: 'FO', stakr: 'Forchheim (Bayern)'},
    {usz: 'FOR', stakr: 'Forst a.d. Lausitz / Landkreis Spree-Neiße (Brandenburg)'},
    {usz: 'FR', stakr: 'Freiburg im Breisgau / Landkreis Breisgau-Hochschwarzwald (Baden-Württemberg)'},
    {usz: 'FRG', stakr: 'Freyung-Grafenau (Bayern)'},
    {usz: 'FRI', stakr: 'Friesland (Niedersachsen)'},
    {usz: 'FRW', stakr: 'Bad Freienwalde a.d. Oder / Landkreis Märkisch-Oderland (Brandenburg)'},
    {usz: 'FS', stakr: 'Freising und Stadt Moosburg an der Isar (Bayern)'},
    {usz: 'FT', stakr: 'Frankenthal in der Pfalz (Rheinland-Pfalz)'},
    {usz: 'FTL', stakr: 'Freital / Landkreis Sächsische Schweiz-Osterzgebirge (Sachsen)'},
    {usz: 'FÜ', stakr: 'Fürth (Bayern)'},
    {usz: 'FÜS', stakr: 'Füssen / Landkreis Ostallgäu (Bayern)'},
    {usz: 'G', stakr: 'Gera (Thüringen)'},
    {usz: 'GA', stakr: 'Gardelegen / Altmarkkreis Salzwedel (Sachsen-Anhalt)'},
    {usz: 'GAN', stakr: 'Bad Gandersheim / Landkreis Northeim (Niedersachsen)'},
    {usz: 'GAP', stakr: 'Garmisch-Partenkirchen (Bayern)'},
    {usz: 'GC', stakr: 'Glauchau / Landkreis Zwickau (Sachsen)'},
    {usz: 'GD', stakr: 'Schwäbisch Gmünd / Ostalbkreis (Baden-Württemberg)'},
    {usz: 'GDB', stakr: 'Gadebusch / Landkreis Nordwestmecklenburg (Mecklenburg-Vorpommern)'},
    {usz: 'GE', stakr: 'Gelsenkirchen (Nordrhein-Westfalen)'},
    {usz: 'GEL', stakr: 'Geldern / Kreis Kleve (Nordrhein-Westfalen)'},
    {usz: 'GEO', stakr: 'Gerolzhofen / Landkreise Haßberge und Schweinfurt (Bayern)'},
    {usz: 'GER', stakr: 'Germersheim (Rheinland-Pfalz)'},
    {usz: 'GF', stakr: 'Gifhorn (Niedersachsen)'},
    {usz: 'GG', stakr: 'Groß-Gerau (Hessen)'},
    {usz: 'GHA', stakr: 'Geithain / Landkreis Leipzig (Sachsen)'},
    {usz: 'GHC', stakr: 'Gräfenhainichen / Landkreis Wittenberg (Sachsen-Anhalt)'},
    {usz: 'GI', stakr: 'Gießen (Hessen)'},
    {usz: 'GK', stakr: 'Geilenkirchen / Kreis Heinsberg (Nordhrein-Westfalen)'},
    {usz: 'GL', stakr: 'Bergisch Gladbach / Rheinisch-Bergischer Kreis (Nordrhein-Westfalen)'},
    {usz: 'GM', stakr: 'Gummersbach / Oberbergischer Kreis (Nordrhein-Westfalen)'},
    {usz: 'GMN', stakr: 'Grimmen / Landkreis Vorpommern-Rügen (Mecklenburg-Vorpommern)'},
    {usz: 'GNT', stakr: 'Genthin / Landkreis Jerichower Land (Sachsen-Anhalt)'},
    {usz: 'GÖ', stakr: 'Göttingen (Niedersachsen)'},
    {usz: 'GOA', stakr: 'Sankt Goar / Rhein-Hunsrück-Kreis (Rheinland-Pfalz)'},
    {usz: 'GOH', stakr: 'Sankt Goarshausen / Rhein-Lahn-Kreis (Rheinland-Pfalz)'},
    {usz: 'GP', stakr: 'Göppingen (Baden-Württemberg)'},
    {usz: 'GR', stakr: 'Görlitz (Sachsen)'},
    {usz: 'GRA', stakr: 'Görlitz (Sachsen)'},
    {usz: 'GRH', stakr: 'Grafenau / Landkreis Freyung-Grafenau (Bayern)'},
    {usz: 'GRI', stakr: 'Bad Griesbach im Rottal / Landkreis Rottal-Inn (Bayern)'},
    {usz: 'GRM', stakr: 'Grimma / Landkreis Leipzig (Sachsen)'},
    {usz: 'GRZ', stakr: 'Greiz (Thüringen)'},
    {usz: 'GS', stakr: 'Goslar (Niedersachsen)'},
    {usz: 'GT', stakr: 'Gütersloh in Rheda-Wiedenbrück (Nordrhein-Westfalen)'},
    {usz: 'GTH', stakr: 'Gotha (Thüringen)'},
    {usz: 'GÜ', stakr: 'Güstrow / Landkreis Rostock (Mecklenburg-Vorpommern)'},
    {usz: 'GUB', stakr: 'Guben / Landkreis Spree-Neiße (Brandenburg)'},
    {usz: 'GUN', stakr: 'Gunzenhausen / Landkreis Weißenburg-Gunzenhausen (Bayern)'},
    {usz: 'GVM', stakr: 'Grevesmühlen / Landkreis Nordwestmecklenburg (Mecklenburg-Vorpommern)'},
    {usz: 'GW', stakr: 'Greifswald / Landkreis Vorpommern-Greifswald (Mecklenburg-Vorpommern)'},
    {usz: 'GZ', stakr: 'Günzburg (Bayern)'},
    {usz: 'H', stakr: 'Hannover (Niedersachsen)'},
    {usz: 'HA', stakr: 'Hagen / Westfalen (Nordrhein-Westfalen)'},
    {usz: 'HAB', stakr: 'Hammelburg / Landkreis Bad Kissingen (Bayern)'},
    {usz: 'HAL', stakr: 'Halle a.d. Saale (Sachsen-Anhalt)'},
    {usz: 'HAM', stakr: 'Hamm (Nordrhein-Westfalen)'},
    {usz: 'HAS', stakr: 'Haßfurt / Landkreis Haßberge (Bayern)'},
    {usz: 'HB', stakr: 'Hansestadt Bremen und Bremerhaven (Bremen)'},
    {usz: 'HBN', stakr: 'Hildburghausen (Thüringen)'},
    {usz: 'HBS', stakr: 'Halberstadt / Landkreis Harz (Sachsen-Anhalt)'},
    {usz: 'HC', stakr: 'Hainichen / Landkreis Mittelsachsen (Sachsen)'},
    {usz: 'HCH', stakr: 'Hechingen / Zollernalbkreis (Baden-Württemberg)'},
    {usz: 'HD', stakr: 'Heidelberg / Rhein-Neckar-Kreis (Baden-Württemberg)'},
    {usz: 'HDH', stakr: 'Heidenheim a.d. Brenz (Baden-Württemberg)'},
    {usz: 'HDL', stakr: 'Haldensleben / Landkreis Börde (Sachsen-Anhalt)'},
    {usz: 'HE', stakr: 'Helmstedt (Niedersachsen)'},
    {usz: 'HEB', stakr: 'Hersbruck / Landkreis Nürnberger Land (Bayern)'},
    {usz: 'HEF', stakr: 'Bad Hersfeld / Landkreis Bad Hersfeld-Rotenburg (Hessen)'},
    {usz: 'HEI', stakr: 'Heide in Holstein / Landkreis Dithmarschen in (Schleswig-Holstein)'},
    {usz: 'HEL', stakr: 'Hessen, Landesregierung und Landtag'},
    {usz: 'HER', stakr: 'Herne (Nordrhein-Westfalen)'},
    {usz: 'HET', stakr: 'Hettstedt / Landkreis Mansfeld-Südharz (Sachsen-Anhalt)'},
    {usz: 'HF', stakr: 'Herford (Nordrhein-Westfalen)'},
    {usz: 'HG', stakr: 'Bad Homburg vor der Höhe / Landkreis Hochtaunuskreis (Hessen)'},
    {usz: 'HGN', stakr: 'Hagenow / Landkreis Ludwigslust-Parchim (Mecklenburg-Vorpommern)'},
    {usz: 'HGW', stakr: 'Hansestadt Greifswald / Landkreis Vorpommern-Greifswald (Mecklenburg-Vorpommern)'},
    {usz: 'HH', stakr: 'Hansestadt Hamburg (Hamburg)'},
    {usz: 'HHM', stakr: 'Hohenmölsen / Burgenlandkreis (Sachsen-Anhalt)'},
    {usz: 'HI', stakr: 'Hildesheim (Niedersachsen)'},
    {usz: 'HIG', stakr: 'Heiligenstadt / Landkreis Eichsfeld (Thüringen)'},
    {usz: 'HIP', stakr: 'Hilpoltstein / Landkreis Roth (Bayern)'},
    {usz: 'HK', stakr: 'Heidekreis (Niedersachsen)'},
    {usz: 'HL', stakr: 'Hansestadt Lübeck (Schleswig-Holstein)'},
    {usz: 'HM', stakr: 'Hameln / Landkreis Hameln-Pyrmont (Niedersachsen)'},
    {usz: 'HMÜ', stakr: 'Hannoversch Münden / Landkreis Göttingen (Niedersachsen)'},
    {usz: 'HN', stakr: 'Heilbronn am Neckar (Baden-Württemberg)'},
    {usz: 'HO', stakr: 'Hof a.d. Saale (Bayern)'},
    {usz: 'HOG', stakr: 'Hofgeismar / Landkreis Kassel (Hessen)'},
    {usz: 'HOH', stakr: 'Hofheim in Unterfranken / Landkreis Haßberge (Bayern)'},
    {usz: 'HOL', stakr: 'Holzminden (Niedersachsen)'},
    {usz: 'HOM', stakr: 'Homburg / Saarland-Pfalz-Kreis (Saarland)'},
    {usz: 'HOR', stakr: 'Horb / Landkreis Freudenstadt (Baden-Württemberg)'},
    {usz: 'HOT', stakr: 'Hohenstein-Ernstthal / Landkreis Zwickau (Sachsen)'},
    {usz: 'HP', stakr: 'Heppenheim / Landkreis Bergstraße (Hessen)'},
    {usz: 'HR', stakr: 'Homberg (Efze) / Schwalm-Eder-Kreis (Hessen)'},
    {usz: 'HRO', stakr: 'Hansestadt Rostock (Mecklenburg-Vorpommern)'},
    {usz: 'HS', stakr: 'Heinsberg (Nordrhein-Westfalen)'},
    {usz: 'HSK', stakr: 'Hochsauerlandkreis (Nordrhein-Westfalen)'},
    {usz: 'HST', stakr: 'Hansestadt Stralsund / Landkreis Vorpommern-Rügen (Mecklenburg-Vorpommern)'},
    {usz: 'HU', stakr: 'Hanau / Main-Kinzig-Kreis (Hessen)'},
    {usz: 'HV', stakr: 'Havelberg / Landkreis Stendal (Sachsen-Anhalt)'},
    {usz: 'HVL', stakr: 'Havelland (Brandenburg)'},
    {usz: 'HWI', stakr: 'Hansestadt Wismar / Landkreis Nordwestmecklenburg (Mecklenburg-Vorpommern)'},
    {usz: 'HX', stakr: 'Höxter (Nordrhein-Westfalen)'},
    {usz: 'HY', stakr: 'Hoyerswerda / Landkreis Bautzen (Sachsen)'},
    {usz: 'HZ', stakr: 'Harz (Sachsen-Anhalt)'},
    {usz: 'IGB', stakr: 'St. Ingbert / Saarpfalz Kreis (Saarland)'},
    {usz: 'IK', stakr: 'Ilm-Kreis (Thüringen)'},
    {usz: 'IL', stakr: 'Ilmenau / Ilm-Kreis (Thüringen)'},
    {usz: 'ILL', stakr: 'Illertissen / Landkreis Neu-Ulm (Bayern)'},
    {usz: 'IN', stakr: 'Ingolstadt a.d. Donau (Bayern)'},
    {usz: 'IZ', stakr: 'Itzehoe / Kreis Steinburg (Schleswig-Holstein)'},
    {usz: 'J', stakr: 'Jena (Thüringen)'},
    {usz: 'JE', stakr: 'Jessen / Landkreis Wittenberg (Sachsen-Anhalt)'},
    {usz: 'JL', stakr: 'Jerichower Land (Sachsen-Anhalt)'},
    {usz: 'JÜL', stakr: 'Jülich / Kreis Düren (Nordrhein-Westfalen)'},
    {usz: 'K', stakr: 'Köln (Nordrhein-Westfalen)'},
    {usz: 'KA', stakr: 'Karlsruhe (Baden-Württemberg)'},
    {usz: 'KB', stakr: 'Korbach / Landkreis Waldeck-Frankenberg (Hessen)'},
    {usz: 'KC', stakr: 'Kronach (Bayern)'},
    {usz: 'KE', stakr: 'Kempten im Allgäu (Bayern)'},
    {usz: 'KEH', stakr: 'Kelheim (Bayern)'},
    {usz: 'KEL', stakr: 'Kehl / Ortenaukreis (Baden-Württemberg)'},
    {usz: 'KEM', stakr: 'Kenath / Landkreise Bayreuth und Tirschenreuth (Bayern)'},
    {usz: 'KF', stakr: 'Kaufbeuren (Bayern)'},
    {usz: 'KG', stakr: 'Bad Kissingen (Bayern)'},
    {usz: 'KH', stakr: 'Bad Kreuznach (Rheinland-Pfalz)'},
    {usz: 'KI', stakr: 'Kiel (Schleswig-Holstein)'},
    {usz: 'KIB', stakr: 'Kirchheimbolanden / Donnersberg-Kreis (Rheinland-Pfalz)'},
    {usz: 'KK', stakr: 'Kempen-Krefeld, Kreis Viersen (Nordrhein-Westfalen)'},
    {usz: 'KL', stakr: 'Kaiserslautern (Rheinland-Pfalz)'},
    {usz: 'KLE', stakr: 'Kleve (Nordrhein-Westfalen)'},
    {usz: 'KLZ', stakr: 'Klötze / Altmarkkreis Salzwedel (Sachsen-Anhalt)'},
    {usz: 'KM', stakr: 'Kamenz / Landkreis Bautzen (Sachsen)'},
    {usz: 'KN', stakr: 'Konstanz (Baden-Württemberg)'},
    {usz: 'KO', stakr: 'Koblenz (Rheinland-Pfalz)'},
    {usz: 'KÖN', stakr: 'Bad Königshofen im Grabfeld / Landkreis Rhön-Grabfeld (Sachsen-Anhalt)'},
    {usz: 'KÖT', stakr: 'Köthen / Landkreis Anhalt-Bitterfeld (Sachsen-Anhalt)'},
    {usz: 'KR', stakr: 'Krefeld (Nordrhein-Westfalen)'},
    {usz: 'KRU', stakr: 'Krumbach in Schwaben / Landkreis Günzburg (Nordrhein-Westfalen)'},
    {usz: 'KS', stakr: 'Kassel (Hessen)'},
    {usz: 'KT', stakr: 'Kitzingen (Bayern)'},
    {usz: 'KU', stakr: 'Kulmbach (Bayern)'},
    {usz: 'KÜN', stakr: 'Künzelsau / Hohenlohe-Kreis (Baden-Württemberg)'},
    {usz: 'KUS', stakr: 'Kusel (Rheinland-Pfalz)'},
    {usz: 'KY', stakr: 'Kyritz / Landkreis Ostprignitz-Ruppin (Brandenburg)'},
    {usz: 'KYF', stakr: 'Kyffhäuserkreis (Thüringen)'},
    {usz: 'L', stakr: 'Leipzig (Sachsen)'},
    {usz: 'LA', stakr: 'Landshut (Bayern)'},
    {usz: 'LAU', stakr: 'Lauf a.d. Pegnitz / Nürnberger Land (Bayern)'},
    {usz: 'LB', stakr: 'Ludwigsburg (Baden-Württemberg)'},
    {usz: 'LBS', stakr: 'Bad Lobenstein / Saale-Orla-Kreis (Thüringen)'},
    {usz: 'LBZ', stakr: 'Lübz / Landkreis Ludwigslust-Parchim (Mecklenburg-Vorpommern)'},
    {usz: 'LD', stakr: 'Landau in der Pfalz / (Rheinland-Pfalz)'},
    {usz: 'LDK', stakr: 'Lahn-Dill-Kreis (Hessen)'},
    {usz: 'LDS', stakr: 'Landkreis Dahme-Spreewald (Brandenburg)'},
    {usz: 'LEO', stakr: 'Leonberg / Landkreis Böblingen (Niedersachsen)'},
    {usz: 'LER', stakr: 'Leer in Ostfriesland (Niedersachsen)'},
    {usz: 'LEV', stakr: 'Leverkusen (Nordrhein-Westfalen)'},
    {usz: 'LG', stakr: 'Lüneburg (Niedersachsen)'},
    {usz: 'LH', stakr: 'Lüdinghausen / Kreis Coesfeld (Nordrhein-Westfalen)'},
    {usz: 'LI', stakr: 'Lindau am Bodensee (Bayern)'},
    {usz: 'LIB', stakr: 'Bad Liebenwerda / Landkreis Elbe-Elster (Brandenburg)'},
    {usz: 'LIF', stakr: 'Lichtenfels (Bayern)'},
    {usz: 'LIP', stakr: 'Kreis Lippe(Nordrhein-Westfalen)'},
    {usz: 'LL', stakr: 'Landsberg am Lech (Bayern)'},
    {usz: 'LM', stakr: 'Limburg a.d. Lahn / Landkreis Limburg-Weilburg(Hessen)'},
    {usz: 'LÖ', stakr: 'Lörrach (Baden-Württemberg)'},
    {usz: 'LÖB', stakr: 'Löbau / Landkreis Görlitz (Sachsen)'},
    {usz: 'LOS', stakr: 'Landkreis Oder-Spree (Brandenburg)'},
    {usz: 'LP', stakr: 'Lippstadt / Kreis Soest (Nordrhein-Westfalen)'},
    {usz: 'LR', stakr: 'Lahr im Schwarzwald / Ortenaukreis (Baden-Württemberg)'},
    {usz: 'LRO', stakr: 'Landkreis Rostock (Mecklenburg-Vorpommern)'},
    {usz: 'LSA', stakr: 'Sachsen-Anhalt Landesregierung und Landtag'},
    {usz: 'LSN', stakr: 'Sachsen, Landesregierung und Landtag'},
    {usz: 'LSZ', stakr: 'Bad Langensalza / Unstrut-Hainich-Kreis (Thüringen)'},
    {usz: 'LU', stakr: 'Ludwigshafen am Rhein (Rheinland-Pfalz)'},
    {usz: 'LÜN', stakr: 'Lünen / Kreis Unna (Nordrhein-Westfalen)'},
    {usz: 'LUP', stakr: 'Ludwigslust-Parchim (Mecklenburg-Vorpommern)'},
    {usz: 'LWL', stakr: 'Ludwigslust (Mecklenburg-Vorpommern)'},
    {usz: 'M', stakr: 'München (Bayern)'},
    {usz: 'MA', stakr: 'Mannheim (Baden-Württemberg)'},
    {usz: 'MAB', stakr: 'Marienberg / Erzgebirgskreis (Sachsen)'},
    {usz: 'MAI', stakr: 'Mainburg / Landkreis Kelheim (Bayern)'},
    {usz: 'MAK', stakr: 'Marktredwitz / Landkreis Wunsiedel im Fichtelgebirge (Bayern)'},
    {usz: 'MAL', stakr: 'Landkreis Mallersdorf (Bayern)'},
    {usz: 'MB', stakr: 'Miesbach (Bayern)'},
    {usz: 'MC', stakr: 'Malchin / Landkreis Mecklenburgische Seenplatte (Mecklenburg-Vorpommern)'},
    {usz: 'MD', stakr: 'Magdeburg (Sachsen-Anhalt)'},
    {usz: 'ME', stakr: 'Mettmann (Nordrhein-Westfalen)'},
    {usz: 'MEI', stakr: 'Meißen (Sachsen)'},
    {usz: 'MEK', stakr: 'Mittlerer Erzgebirgskreis (Sachsen)'},
    {usz: 'MER', stakr: 'Merseburg / Saalekreis (Sachsen-Anhalt)'},
    {usz: 'MET', stakr: 'Mellrichstadt / Landkreis Rhön-Grabfeld (Bayern)'},
    {usz: 'MG', stakr: 'Mönchengladbach (Nordrhein-Westfalen)'},
    {usz: 'MGH', stakr: 'Bad Mergentheim / Main-Tauber-Kreis (Baden-Württemberg)'},
    {usz: 'MGN', stakr: 'Meiningen / Landkreis Schmalkalden-Meiningen (Thüringen)'},
    {usz: 'MH', stakr: 'Mülheim/Ruhr (Nordrhein-Westfalen)'},
    {usz: 'MHL', stakr: 'Mühlhausen / Unstrut-Hainich-Kreis (Thüringen)'},
    {usz: 'MI', stakr: 'Minden / Kreis Minden-Lübbecke (Nordrhein-Westfalen)'},
    {usz: 'MIL', stakr: 'Miltenberg (Bayern)'},
    {usz: 'MK', stakr: 'Mark / Märkischer Kreis (Nordrhein-Westfalen)'},
    {usz: 'MKK', stakr: 'Main-Kinzig-Kreis (Hessen)'},
    {usz: 'ML', stakr: 'Mansfelder Land / Landkreis Mansfeld-Südharz (Sachsen-Anhalt)'},
    {usz: 'MM', stakr: 'Memmingen (Bayern)'},
    {usz: 'MN', stakr: 'Mindelheim / Landkreis Unterallgäu (Bayern)'},
    {usz: 'MO', stakr: 'Moers / Kreis Wesel (Nordrhein-Westfalen)'},
    {usz: 'MOD', stakr: 'Marktoberdorf / Landkreis Ostallgäu (Bayern)'},
    {usz: 'MOL', stakr: 'Märkisch-Oderland (Brandenburg)'},
    {usz: 'MON', stakr: 'Monschau / Städteregion Aachen (Nordrhein-Westfalen)'},
    {usz: 'MOS', stakr: 'Mosbach / Neckar-Odenwald-Kreis (Baden-Württemberg)'},
    {usz: 'MQ', stakr: 'Merseburg-Querfurt / Saalekreis (Baden-Württemberg)'},
    {usz: 'MR', stakr: 'Marburg / Landkreis Marburg-Biedenkopf (Hessen)'},
    {usz: 'MS', stakr: 'Münster (Nordrhein-Westfalen)'},
    {usz: 'MSE', stakr: 'Mecklenburgische Seenplatte (Mecklenburg-Vorpommern)'},
    {usz: 'MSH', stakr: 'Mansfeld-Südharz (Sachsen-Anhalt)'},
    {usz: 'MSP', stakr: 'Main-Spessart-Kreis (Bayern)'},
    {usz: 'MST', stakr: 'Mecklenburg-Strelitz / Landkreis Mecklenburgische Seenplatte (Mecklenburg-Vorpommern)'},
    {usz: 'MTL', stakr: 'Muldentalkreis (Sachsen)'},
    {usz: 'MTK', stakr: 'Main-Taunus-Kreis (Hessen)'},
    {usz: 'MÜ', stakr: 'Mühldorf am Inn (Bayern)'},
    {usz: 'MÜB', stakr: 'Münchberg / Landkreis Bayreuth (Bayern)'},
    {usz: 'MÜR', stakr: 'Müritz / Landkreis Mecklenburgische Seenplatte (Mecklenburg-Vorpommern)'},
    {usz: 'MVL', stakr: 'Mecklenburg-Vorpommern Landesregierung und Landtag'},
    {usz: 'MW', stakr: 'Mittweida / Landkreis Mittelsachsen (Sachsen)'},
    {usz: 'MY', stakr: 'Mayen / Landkreis Mayen-Koblenz (Rheinland-Pfalz)'},
    {usz: 'MYK', stakr: 'Mayen-Koblenz (Rheinland-Pfalz)'},
    {usz: 'MZ', stakr: 'Mainz / Landkreis Mainz-Bingen (Rheinland-Pfalz)'},
    {usz: 'MZG', stakr: 'Merzig / Landkreis Merzig-Wadern (Saarland)'},
    {usz: 'N', stakr: 'Nürnberg (Bayern)'},
    {usz: 'NAB', stakr: 'Nabburg / Landkreise Amberg-sulzbach und Schwandorf (Bayern)'},
    {usz: 'NAI', stakr: 'Naila / Landkreis Hof (Bayern)'},
    {usz: 'NB', stakr: 'Neubrandenburg (Mecklenburg-Vorpommern)'},
    {usz: 'ND', stakr: 'Neuburg a.d. Donau / Landkreise Neuburg-Schrobenhausen (Bayern)'},
    {usz: 'NDH', stakr: 'Nordhausen (Thüringen)'},
    {usz: 'NE', stakr: 'Neuss / Rhein-Kreis Neuss (Nordrhein-Westfalen)'},
    {usz: 'NEA', stakr: 'Neustadt a.d. Aisch / Landkreis Neustadt a.d. Aisch-Bad Windsheim (Bayern)'},
    {usz: 'NEB', stakr: 'Nebra im Unstruttal / Burgenlandkreis (Sachsen-Anhalt)'},
    {usz: 'NEC', stakr: 'Neustadt bei Coburg / Landkreis Coburg (Bayern)'},
    {usz: 'NEN', stakr: 'Neunburg vorm Wald / Landkreis Schwandorf (Bayern)'},
    {usz: 'NES', stakr: 'Bad Neustadt a.d. Saale / Landkreis Rhön-Grabfeld (Bayern)'},
    {usz: 'NEW', stakr: 'Neustadt a.d. Waldnaab (Bayern)'},
    {usz: 'NF', stakr: 'Nordfriesland (Schleswig-Holstein)'},
    {usz: 'NH', stakr: 'Neuhaus am Rennweg / Landkreis Sonneberg (Thüringen)'},
    {usz: 'NI', stakr: 'Nienburg a.d. Weser (Niedersachsen)'},
    {usz: 'NK', stakr: 'Neunkirchen (Saarland)'},
    {usz: 'NL', stakr: 'Niedersächsische Landesregierung und Landtag'},
    {usz: 'NM', stakr: 'Neumarkt in der Oberpfalz (Bayern)'},
    {usz: 'NMB', stakr: 'Naumburg a.d. Saale / Burgenlandkreis (Sachsen-Anhalt)'},
    {usz: 'NMS', stakr: 'Neumünster (Schleswig-Holstein)'},
    {usz: 'NÖ', stakr: 'Nördlingen / Landkreis Donau-Ries (Bayern)'},
    {usz: 'NOH', stakr: 'Nordhorn / Landkreis Grafschaft Bentheim (Niedersachsen)'},
    {usz: 'NOL', stakr: 'Niederschlesische Oberlausitz / Landkreis Görlitz (Sachsen)'},
    {usz: 'NOM', stakr: 'Northeim (Niedersachsen)'},
    {usz: 'NOR', stakr: 'Norden / Landkreis Aurich (Niedersachsen)'},
    {usz: 'NP', stakr: 'Neuruppin / Landkreis Ostprignitz-Ruppin (Brandenburg)'},
    {usz: 'NR', stakr: 'Neuwied am Rhein (Rheinland-Pfalz)'},
    {usz: 'NRW', stakr: 'Nordrhein-Westfalen Landesregierung, Landtag und Polizei'},
    {usz: 'NU', stakr: 'Neu-Ulm (Bayern)'},
    {usz: 'NVP', stakr: 'Nordvorpommern / Landkreis Vorpommern-Rügen (Mecklenburg-Vorpommern)'},
    {usz: 'NW', stakr: 'Neustadt a.d. Weinstraße (Rheinland-Pfalz)'},
    {usz: 'NWM', stakr: 'Nordwestmecklenburg (Mecklenburg-Vorpommern)'},
    {usz: 'NY', stakr: 'Niesky Landkreis Görlitz (Sachsen)'},
    {usz: 'NZ', stakr: 'Neustrelitz / Landkreis Mecklenburgische Seenplatte (Mecklenburg-Vorpommern)'},
    {usz: 'OA', stakr: 'Oberallgäu (Bayern)'},
    {usz: 'OAL', stakr: 'Ostallgäu (Bayern)'},
    {usz: 'OB', stakr: 'Oberhausen (Nordrhein-Westfalen)'},
    {usz: 'OBG', stakr: 'Osterburg / Landkreis Stendal (Sachsen-Anhalt)'},
    {usz: 'OC', stakr: 'Oschersleben a.d. Bode / Landkreis Börde (Sachsen-Anhalt)'},
    {usz: 'OCH', stakr: 'Ochsenfurt / Landkreis Würzburg (Bayern)'},
    {usz: 'OD', stakr: 'Bad Oldesloe / Kreis Stormarn (Schleswig-Holstein)'},
    {usz: 'OE', stakr: 'Olpe (Nordrhein-Westfalen)'},
    {usz: 'OF', stakr: 'Offenbach am Main (Hessen)'},
    {usz: 'OG', stakr: 'Offenburg / Ortenaukreis (Baden-Württemberg)'},
    {usz: 'OH', stakr: 'Ostholstein (Schleswig-Holstein)'},
    {usz: 'OHA', stakr: 'Osterode am Harz (Niedersachsen)'},
    {usz: 'OHV', stakr: 'Oberhavel (Brandenburg)'},
    {usz: 'OHZ', stakr: 'Osterholz-Scharmbeck / Landkreis Osterholz (Niedersachsen)'},
    {usz: 'OK', stakr: 'Ohrekreis / Landkreis Börde (Sachsen-Anhalt)'},
    {usz: 'OL', stakr: 'Oldenburg (Niedersachsen)'},
    {usz: 'OPR', stakr: 'Ostprignitz-Ruppin (Brandenburg)'},
    {usz: 'OR', stakr: 'Oranienburg (Brandenburg)'},
    {usz: 'OS', stakr: 'Osnabrück (Niedersachsen)'},
    {usz: 'OSL', stakr: 'Oberspreewald-Lausitz (Brandenburg)'},
    {usz: 'OVI', stakr: 'Oberviechtach / Landkreis Schwandorf (Bayern)'},
    {usz: 'OVL', stakr: 'Obervogtland in Klingenthal und Ölsnitz (Sachsen)'},
    {usz: 'OVL', stakr: 'Obervogtland / Vogtlandkreis (Sachsen)'},
    {usz: 'OZ', stakr: 'Oschatz / Landkreis Nordsachsen (Sachsen)'},
    {usz: 'P', stakr: 'Potsdam (Brandenburg)'},
    {usz: 'PA', stakr: 'Passau (Bayern)'},
    {usz: 'PAF', stakr: 'Pfaffenhofen a.d. Ilm (Bayern)'},
    {usz: 'PAN', stakr: 'Pfarrkirchen / Landkreis Rottal-Inn (Bayern)'},
    {usz: 'PAR', stakr: 'Parsberg / Landkreis Neumarkt in der Oberpfalz (Bayern)'},
    {usz: 'PB', stakr: 'Paderborn (Nordrhein-Westfalen)'},
    {usz: 'PCH', stakr: 'Parchim / Landkreis Ludwigslust-Parchim (Mecklenburg-Vorpommern)'},
    {usz: 'PE', stakr: 'Peine (Niedersachsen)'},
    {usz: 'PEG', stakr: 'Pegnitz / Landkreise Bayreuth, Forchenheim und Nürnberger Land (Bayern)'},
    {usz: 'PF', stakr: 'Pforzheim / Enzkreis (Baden-Württemberg)'},
    {usz: 'PI', stakr: 'Pinneberg (Schleswig-Holstein)'},
    {usz: 'PIR', stakr: 'Pirna / Landkreis Sächsische Schweiz-Osterzgebirge (Sachsen)'},
    {usz: 'PL', stakr: 'Plauen / Vogtlandkreis (Sachsen)'},
    {usz: 'PLÖ', stakr: 'Plön (Schleswig-Holstein)'},
    {usz: 'PM', stakr: 'Potsdam-Mittelmark (Brandenburg)'},
    {usz: 'PN', stakr: 'Pößneck / Saale-Orla-Kreis (Thüringen)'},
    {usz: 'PR', stakr: 'Prignitz (Brandenburg)'},
    {usz: 'PRÜ', stakr: 'Prüm / Eifelkreis Bitburg-Prüm (Rheinland-Pfalz)'},
    {usz: 'PS', stakr: 'Pirmasens / Landkreis Südwestpfalz (Rheinland-Pfalz)'},
    {usz: 'PW', stakr: 'Pasewalk / Landkreis Vormpommern-Greifswald (Mecklenburg-Vorpommern)'},
    {usz: 'PZ', stakr: 'Prenzlau / Landkreis Uckermark (Brandenburg)'},
    {usz: 'QFT', stakr: 'Querfurt / Saalekreis (Sachsen-Anhalt)'},
    {usz: 'QLB', stakr: 'Quedlinburg / Landkreis Harz (Sachsen-Anhalt)'},
    {usz: 'R', stakr: 'Regensburg (Bayern)'},
    {usz: 'RA', stakr: 'Rastatt (Baden-Württemberg)'},
    {usz: 'RC', stakr: 'Reichenbach / Vogtlandkreis (Sachsen)'},
    {usz: 'RD', stakr: 'Rendsburg / Landkreis Rendsburg-Eckernförde (Schleswig-Holstein)'},
    {usz: 'RDG', stakr: 'Ribnitz-Damgarten / Landkreis Vorpommern-Rügen (Mecklenburg-Vorpommern)'},
    {usz: 'RE', stakr: 'Recklinghausen (Nordrhein-Westfalen)'},
    {usz: 'REG', stakr: 'Regen (Bayern)'},
    {usz: 'REH', stakr: 'Rehau / Landkreis Wunsiedel im Fichtelgebirge (Bayern)'},
    {usz: 'RG', stakr: 'Riesa-Großenhain / Landkreis Meißen (Sachsen)'},
    {usz: 'RH', stakr: 'Roth (Bayern)'},
    {usz: 'RI', stakr: 'Rinteln / Landkreis Schaumburg (Niedersachsen)'},
    {usz: 'RID', stakr: 'Riedenburg / Landkreis Kelheim (Bayern)'},
    {usz: 'RIE', stakr: 'Riesa / Landkreis Meißen (Sachsen)'},
    {usz: 'RL', stakr: 'Rochlitz / Landkreis Mittelsachsen (Sachsen)'},
    {usz: 'RM', stakr: 'Röbel a.d. Müritz / Landkreis Mecklenburgische Seenplatte (Mecklenburg-Vorpommern)'},
    {usz: 'RO', stakr: 'Rosenheim (Bayern)'},
    {usz: 'ROD', stakr: 'Roding / Landkreise Cham und Schwandorf (Bayern)'},
    {usz: 'ROF', stakr: 'Rotenburg a.d. Fulda / Landkreis Hersfeld-Rotenburg (Hessen)'},
    {usz: 'ROK', stakr: 'Rockenhausen / Donnersbergkreis (Rheinland-Pfalz)'},
    {usz: 'ROL', stakr: 'Rottenburg a.d. Laaber / Landkreis Kelheim (Bayern)'},
    {usz: 'ROS', stakr: 'Rostock (Mecklenburg-Vorpommern)'},
    {usz: 'ROT', stakr: 'Rothenburg ob der Tauber / Landkreis Ansbach (Bayern)'},
    {usz: 'ROW', stakr: 'Rotenburg a.d. Wümme (Niedersachsen)'},
    {usz: 'RP', stakr: 'Rhein-Pfalz-Kreis'},
    {usz: 'RPL', stakr: 'Rheinland-Pfalz Landesregierung, Landtag und Polizei'},
    {usz: 'RS', stakr: 'Remscheid (Nordrhein-Westfalen)'},
    {usz: 'RSL', stakr: 'Roßlau a.d. Elbe / Stadt Dessau-Roßlau (Sachsen-Anhalt)'},
    {usz: 'RT', stakr: 'Reutlingen (Baden-Württemberg)'},
    {usz: 'RU', stakr: 'Rudolstadt / Landkreis Saalfeld-Rudolfstadt (Thüringen)'},
    {usz: 'RÜD', stakr: 'Rüdesheim / Rheingau-Taunus-Kreis (Hessen)'},
    {usz: 'RÜG', stakr: 'Rügen / Landkreis Vorpommern-Rügen (Mecklenburg-Vorpommern)'},
    {usz: 'RV', stakr: 'Ravensburg (Baden-Württemberg)'},
    {usz: 'RW', stakr: 'Rottweil (Baden-Württemberg)'},
    {usz: 'RZ', stakr: 'Ratzeburg / Kreis Herzogtum Lauenburg (Schleswig-Holstein)'},
    {usz: 'S', stakr: 'Stuttgart (Baden-Württemberg)'},
    {usz: 'SAB', stakr: 'Saarburg / Landkreis Trier-Saarburg (Rheinland-Pfalz)'},
    {usz: 'SAD', stakr: 'Schwandorf (Bayern)'},
    {usz: 'SAL', stakr: 'Saarland, Landesregierung, Landtag und Polizei (Saarland)'},
    {usz: 'SAN', stakr: 'Stadtsteinach / Landkreise Kronach und Kulmbach (Bayern)'},
    {usz: 'SAW', stakr: 'Salzwedel / Altmarkkreis (Sachsen-Anhalt)'},
    {usz: 'SB', stakr: 'Saarbrücken (Saarland)'},
    {usz: 'SBG', stakr: 'Strasburg / Landkreis Vorpommern-Greifswald (Mecklenburg-Vorpommern)'},
    {usz: 'SBK', stakr: 'Schönebeck a.d. Elbe / Salzlandkreis (Sachsen-Anhalt)'},
    {usz: 'SC', stakr: 'Schwabach (Bayern)'},
    {usz: 'SCZ', stakr: 'Schleiz / Saale-Orla-Kreis (Thüringen)'},
    {usz: 'SDH', stakr: 'Sondershausen / Kyffhäuserkreis (Thüringen)'},
    {usz: 'SDL', stakr: 'Stendal (Sachsen-Anhalt)'},
    {usz: 'SDT', stakr: 'Schwedt a.d. Oder / Landkreis Uckermark (Brandenburg)'},
    {usz: 'SE', stakr: 'Bad Segeberg / Kreis Segeberg (Schleswig-Holstein)'},
    {usz: 'SEB', stakr: 'Sebnitz / Landkreis Sächsische Schweiz-Osterzgebirge (Sachsen)'},
    {usz: 'SEE', stakr: 'Seelow / Landkreis Märkisch-Oderland (Brandenburg)'},
    {usz: 'SEF', stakr: 'Scheinfeld / Landkreis Neustadt an der Aisch-Bad Windsheim (Bayern)'},
    {usz: 'SEL', stakr: 'Selb / Landkreis Wunsiedel im Fichtelgebirge (Bayern)'},
    {usz: 'SFB', stakr: 'Senftenberg / Landkreis Oberspreewald-Lausitz (Brandenburg)'},
    {usz: 'SFT', stakr: 'Staßfurt / Salzlandkreis (Sachsen-Anhalt)'},
    {usz: 'SG', stakr: 'Solingen (Nordrhein-Westfalen)'},
    {usz: 'SGH', stakr: 'Sangerhausen / Landkreis Mansfeld-Südharz (Sachsen-Anhalt)'},
    {usz: 'SH', stakr: 'Schleswig-Holstein Landesregierung, Landtag und Polizei (Schleswig-Holstein)'},
    {usz: 'SHA', stakr: 'Schwäbisch Hall (Baden-Württemberg)'},
    {usz: 'SHG', stakr: 'Schaumburg oder Stadthagen (Niedersachsen)'},
    {usz: 'SHK', stakr: 'Saale-Holzland-Kreis (Thüringen)'},
    {usz: 'SHL', stakr: 'Suhl (Thüringen)'},
    {usz: 'SI', stakr: 'Siegen / Kreis Siegen-Wittgenstein (Nordrhein-Westfalen)'},
    {usz: 'SIG', stakr: 'Sigmaringen (Baden-Württemberg)'},
    {usz: 'SIM', stakr: 'Simmern / Rhein-Hunsrück-Kreis (Rheinland-Pfalz)'},
    {usz: 'SK', stakr: 'Saalkreis (Sachsen-Anhalt)'},
    {usz: 'SL', stakr: 'Schleswig / Kreis Schleswig-Flensburg (Schleswig-Holstein)'},
    {usz: 'SLE', stakr: 'Schleiden / Kreis Euskirchen (Nordrhein-Westfalen)'},
    {usz: 'SLF', stakr: 'Saalfeld a.d. Saale / Landkreis Saalfeld-Rudolstadt (Thüringen)'},
    {usz: 'SLK', stakr: 'Salzlandkreis (Sachsen-Anhalt)'},
    {usz: 'SLN', stakr: 'Schmölln / Landkreis Altenburger Land (Thüringen)'},
    {usz: 'SLS', stakr: 'Saarlouis (Saarland)'},
    {usz: 'SLÜ', stakr: 'Schlüchtern / Main-Kinzig-Kreis (Hessen)'},
    {usz: 'SLZ', stakr: 'Bad Salzungen / Wartburgkreis (Thüringen)'},
    {usz: 'SM', stakr: 'Schmalkalden-Meiningen (Thüringen)'},
    {usz: 'SN', stakr: 'Schwerin (Mecklenburg-Vorpommern)'},
    {usz: 'SO', stakr: 'Soest (Nordrhein-Westfalen)'},
    {usz: 'SOB', stakr: 'Schrobenhausen / Landkreis Neuburg-Schrobenhausen (Bayern)'},
    {usz: 'SOG', stakr: 'Schongau / Landkreis Weilheim-Schongau (Bayern)'},
    {usz: 'SOK', stakr: 'Saale-Orla-Kreis (Thüringen)'},
    {usz: 'SÖM', stakr: 'Sömmerda (Thüringen)'},
    {usz: 'SON', stakr: 'Sonneberg (Thüringen)'},
    {usz: 'SP', stakr: 'Speyer (Rheinland-Pfalz)'},
    {usz: 'SPB', stakr: 'Spremberg / Landkreis Spree-Neiße (Brandenburg)'},
    {usz: 'SPN', stakr: 'Spree-Neiße (Brandenburg)'},
    {usz: 'SR', stakr: 'Straubing / Landkreis Straubing-Bogen (Bayern)'},
    {usz: 'SRB', stakr: 'Strausberg / Landkreis Märkisch-Oderland (Brandenburg)'},
    {usz: 'SRO', stakr: 'Stadtroda / Saale-Holzland-Kreis (Thüringen)'},
    {usz: 'ST', stakr: 'Steinfurt (Nordrhein-Westfalen)'},
    {usz: 'STA', stakr: 'Starnberg (Bayern)'},
    {usz: 'STB', stakr: 'Sternberg / Landkreis Ludwigslust-Parchim (Mecklenburg-Vorpommern)'},
    {usz: 'STD', stakr: 'Stade (Niedersachsen)'},
    {usz: 'STE', stakr: 'Bad Staffelstein / Landkreis Lichtenfels (Bayern)'},
    {usz: 'STL', stakr: 'Stollberg / Erzgebirgskreis (Sachsen)'},
    {usz: 'SU', stakr: 'Siegburg / Rhein-Sieg-Kreis (Nordrhein-Westfalen)'},
    {usz: 'SUL', stakr: 'Sulzbach-Rosenberg / Landkreis Amberg-Sulzbach (Bayern)'},
    {usz: 'SÜW', stakr: 'Südliche Weinstraße (Rheinland-Pfalz)'},
    {usz: 'SW', stakr: 'Schweinfurt (Bayern)'},
    {usz: 'SWA', stakr: 'Bad Schwalbach / Rheingau-Taunus-Kreis (Hessen)'},
    {usz: 'SZ', stakr: 'Salzgitter (Niedersachsen)'},
    {usz: 'SZB', stakr: 'Schwarzenberg / Erzgebirgskreis (Sachsen)'},
    {usz: 'TBB', stakr: 'Tauberbischofsheim / Main-Tauber-Kreis (Baden-Württemberg)'},
    {usz: 'TDO', stakr: 'Torgau, Delitzsch, Oschatz / Landkreis Nordsachsen (Sachsen)'},
    {usz: 'TE', stakr: 'Tecklenburg / Kreis Steinfurt (Nordrhein-Westfalen)'},
    {usz: 'TET', stakr: 'Teterow / Landkreis Rostock (Mecklenburg-Vorpommern)'},
    {usz: 'TF', stakr: 'Teltow-Fläming (Brandenburg)'},
    {usz: 'TG', stakr: 'Torgau / Landkreis Nordsachsen (Sachsen)'},
    {usz: 'THL', stakr: 'Thüringen Landesregierung und Landtag (Thüringen)'},
    {usz: 'THW', stakr: 'Bundesanstalt Technisches Hilfswerk (bundesweit)'},
    {usz: 'TIR', stakr: 'Tirschenreuth (Bayern)'},
    {usz: 'TO', stakr: 'Torgau-Oschatz / Landkreis Nordsachsen (Sachsen)'},
    {usz: 'TÖL', stakr: 'Bad Tölz / Landkreis Bad Tölz-Wolfratshausen (Bayern)'},
    {usz: 'TP', stakr: 'Templin / Landkreis Uckermark (Brandenburg)'},
    {usz: 'TR', stakr: 'Trier / Landkreis Trier-Saarburg (Rheinland-Pfalz)'},
    {usz: 'TS', stakr: 'Traunstein (Bayern)'},
    {usz: 'TÜ', stakr: 'Tübingen (Baden-Württemberg)'},
    {usz: 'TUT', stakr: 'Tuttlingen (Baden-Württemberg)'},
    {usz: 'UE', stakr: 'Uelzen (Niedersachsen)'},
    {usz: 'UEM', stakr: 'Ueckermünde / Landkreis Vorpommern-Greifswald (Mecklenburg-Vorpommern)'},
    {usz: 'UFF', stakr: 'Uffenheim / Landkreis Neustadt (Mittelfranken / Bayern)'},
    {usz: 'UH', stakr: 'Unstrut-Hainich (Thüringen)'},
    {usz: 'UL', stakr: 'Ulm / Alb-Donau-Kreis (Baden-Württemberg)'},
    {usz: 'UM', stakr: 'Uckermark (Brandenburg)'},
    {usz: 'UN', stakr: 'Unna (Nordrhein-Westfalen)'},
    {usz: 'USI', stakr: 'Usingen / Hochtaunuskreis (Hessen)'},
    {usz: 'V', stakr: 'Vogtland (Sachsen)'},
    {usz: 'VAI', stakr: 'Vaihingen an der Enz / Landkreis Ludwigsburg (Baden-Württemberg)'},
    {usz: 'VB', stakr: 'Vogelsbergkreis (Hessen)'},
    {usz: 'VEC', stakr: 'Vechta (Niedersachsen)'},
    {usz: 'VER', stakr: 'Verden a.d. Aller (Niedersachsen)'},
    {usz: 'VG', stakr: 'Landkreis Vorpommern-Greifswald (Mecklenburg-Vorpommern)'},
    {usz: 'VIB', stakr: 'Vilsbiburg / Landkreis Rottal-Inn (Bayern)'},
    {usz: 'VIE', stakr: 'Viersen (Nordrhein-Westfalen)'},
    {usz: 'VK', stakr: 'Völklingen / Regionalverband Saarbrücken (Saarland)'},
    {usz: 'VOH', stakr: 'Vohenstrauß / Landkreis Neustadt an der Waldnaab (Bayern)'},
    {usz: 'VR', stakr: 'Landkreis Vorpommern-Rügen (Mecklenburg-Vorpommern)'},
    {usz: 'VS', stakr: 'Villingen-Schwenningen / Schwarzwald-Baar-Kreis (Baden-Württemberg)'},
    {usz: 'W', stakr: 'Wuppertal (Nordrhein-Westfalen)'},
    {usz: 'WA', stakr: 'Waldeck / Landkreis Waldeck-Frankenberg (Hessen)'},
    {usz: 'WAF', stakr: 'Warendorf (Nordrhein-Westfalen)'},
    {usz: 'WAK', stakr: 'Wartburgkreis (Thüringen)'},
    {usz: 'WAN', stakr: 'Wanne-Eickel / Stadt Herne (Nordrhein-Westfalen)'},
    {usz: 'WAT', stakr: 'Wattenscheid / Stadt Bochum (Nordrhein-Westfalen)'},
    {usz: 'WB', stakr: 'Wittenberg (Sachsen-Anhalt)'},
    {usz: 'WBS', stakr: 'Worbis / Landkreis Eichsfeld (Thüringen)'},
    {usz: 'WDA', stakr: 'Werdau / Landkreis Zwickau (Sachsen)'},
    {usz: 'WE', stakr: 'Weimar (Thüringen)'},
    {usz: 'WEL', stakr: 'Weilburg / Landkreis Limburg-Weilburg (Hessen)'},
    {usz: 'WEN', stakr: 'Weiden in der Oberpfalz (Bayern)'},
    {usz: 'WER', stakr: 'Wertingen / Landkreis Dillingen a.d. Donau (Bayern)'},
    {usz: 'WES', stakr: 'Wesel (Nordrhein-Westfalen)'},
    {usz: 'WF', stakr: 'Wolfenbüttel (Niedersachsen)'},
    {usz: 'WHV', stakr: 'Wilhelmshaven (Niedersachsen)'},
    {usz: 'WI', stakr: 'Wiesbaden und Hessische Polizei (Hessen)'},
    {usz: 'WIL', stakr: 'Wittlich a.d. Mosel / Landkreis Bernkastel-Wittlich (Rheinland-Pfalz)'},
    {usz: 'WIS', stakr: 'Wismar / Landkreis Nordwestmecklenburg (Mecklenburg-Vorpommern)'},
    {usz: 'WIT', stakr: 'Witten / Ennepe-Ruhr-Kreis (Nordrhein-Westfalen)'},
    {usz: 'WK', stakr: 'Wittstock a.d. Dosse / Landkreis Ostprignitz-Ruppin (Brandenburg)'},
    {usz: 'WL', stakr: 'Winsen a.d. Luhe / Landkreis Harburg (Niedersachsen)'},
    {usz: 'WLG', stakr: 'Wolgast / Landkreis Vorpommern-Greifswald (Mecklenburg-Vorpommern)'},
    {usz: 'WM', stakr: 'Weilheim / Landkreis Weilheim-Schongau (Bayern)'},
    {usz: 'WMS', stakr: 'Wolmirstedt / Landkreis Börde (Sachsen-Anhalt)'},
    {usz: 'WN', stakr: 'Waiblingen / Rems-Murr-Kreis (Baden-Württemberg)'},
    {usz: 'WND', stakr: 'St. Wendel (Saarland)'},
    {usz: 'WO', stakr: 'Worms (Rheinland-Pfalz)'},
    {usz: 'WOB', stakr: 'Wolfsburg (Niedersachsen)'},
    {usz: 'WOH', stakr: 'Wolfhagen / Landkreis Kassel (Hessen)'},
    {usz: 'WOL', stakr: 'Wolfach / Ortenaukreis (Baden-Württemberg)'},
    {usz: 'WOR', stakr: 'Wolfratshausen / Landkreise München, Starnberg und Bad-Tölz-Wolfratshausen (Bayern)'},
    {usz: 'WOS', stakr: 'Wolfstein / Landkreis Freyung-Grafenau (Bayern)'},
    {usz: 'WR', stakr: 'Wernigerode / Landkreis Harz (Sachsen-Anhalt)'},
    {usz: 'WRN', stakr: 'Waren a.d. Müritz / Landkreis Mecklenburgische Seenplatte (Mecklenburg-Vorpommern)'},
    {usz: 'WS', stakr: 'Wasserburg am Inn / Landkreis Rosenheim (Bayern)'},
    {usz: 'WSF', stakr: 'Weißenfels / Burgenlandkreis (Sachsen-Anhalt)'},
    {usz: 'WST', stakr: 'Westerstede / Landkreis Ammerland (Niedersachsen)'},
    {usz: 'WSW', stakr: 'Weißwasser / Landkreis Görlitz (Sachsen)'},
    {usz: 'WT', stakr: 'Waldshut-Tiengen / Landkreis Waldshut (Baden-Württemberg)'},
    {usz: 'WTM', stakr: 'Wittmund (Niedersachsen)'},
    {usz: 'WÜ', stakr: 'Würzburg, Polizei Unterfranken (Bayern)'},
    {usz: 'WUG', stakr: 'Weißenburg / Landkreis Weißenburg-Gunzenhausen (Bayern)'},
    {usz: 'WÜM', stakr: 'Waldmünchen / Landkreis Cham (Bayern)'},
    {usz: 'WUN', stakr: 'Wunsiedel im Fichtelgebirge (Bayern)'},
    {usz: 'WUR', stakr: 'Wurzen / Landkreis Leipzig(Sachsen)'},
    {usz: 'WW', stakr: 'Westerwald / Westerwaldkreis (Rheinland-Pfalz)'},
    {usz: 'WZ', stakr: 'Wetzlar / Lahn-Dill-Kreis (Hessen)'},
    {usz: 'WIZ', stakr: 'Witzenhausen / Werra-Meißner-Kreis (Hessen)'},
    {usz: 'WZL', stakr: 'Wanzleben / Landkreis Börde (Sachsen-Anhalt)'},
    {usz: 'X', stakr: 'Bundeswehr für NATO-Hauptquartiere'},
    {usz: 'Y', stakr: 'Bundeswehr'},
    {usz: 'Z', stakr: 'Zwickauer Land (Sachsen)'},
    {usz: 'ZE', stakr: 'Zerbst / Landkreis Anhalt-Bitterfeld (Sachsen-Anhalt)'},
    {usz: 'ZEL', stakr: 'Zell a.d. Mosel / Landkreis Cochem-Zell (Rheinland-Pfalz)'},
    {usz: 'ZI', stakr: 'Zittau / Landkreis Görlitz (Sachsen)'},
    {usz: 'ZP', stakr: 'Zschopau / Erzgebirgskreis (Sachsen)'},
    {usz: 'ZR', stakr: 'Zeulenroda / Landkreis Greiz (Thüringen)'},
    {usz: 'ZW', stakr: 'Zweibrücken (Rheinland-Pfalz)'},
    {usz: 'ZZ', stakr: 'Zeitz / Burgenlandkreis (Sachsen-Anhalt)'}
];
